CREATE TABLE api_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image VARCHAR NOT NULL,
    name TEXT NOT NULL,
    region TEXT NOT NULL,
    wine_type TEXT NOT NULL,
    rating decimal NOT NULL
);